const people=[
  {name:"Michael Jordan",cat:"Athlete",photo:"famous_people_images/1.jpg",fact:"<strong>6x NBA champion.</strong> Cut from his high school varsity team sophomore year. Went on to become the gold standard every athlete is measured against."},
  {name:"Oprah Winfrey",cat:"Entertainer",photo:"famous_people_images/2.jpg",fact:"<strong>Billionaire media mogul.</strong> Grew up in poverty in rural Mississippi. Her talk show ran for 25 years and is the highest-rated in TV history."},
  {name:"Beyoncé",cat:"Musician",photo:"famous_people_images/3.jpg",fact:"<strong>32 Grammy Awards.</strong> Most awarded artist in Grammy history. Started in Destiny's Child before going solo."},
  {name:"Muhammad Ali",cat:"Athlete",photo:"famous_people_images/4.jpg",fact:"<strong>3x world heavyweight champion.</strong> Refused military draft, stripped of his title, came back and won it twice more."},
  {name:"Marilyn Monroe",cat:"Entertainer",photo:"famous_people_images/5.jpg",fact:"<strong>Cultural icon of the 1950s–60s.</strong> Born Norma Jeane Mortenson. Famously sang 'Happy Birthday' to President JFK in 1962."},
  {name:"Barack Obama",cat:"Historical / Political",photo:"famous_people_images/6.jpg",fact:"<strong>44th U.S. President.</strong> First African American president. Nobel Peace Prize winner in 2009."},
  {name:"Nelson Mandela",cat:"Historical / Political",photo:"famous_people_images/7.jpg",fact:"<strong>First democratically elected president of South Africa.</strong> Spent 27 years in prison for anti-apartheid activism."},
  {name:"Albert Einstein",cat:"Historical / Political",photo:"famous_people_images/8.jpg",fact:"<strong>Developed the theory of relativity.</strong> Failed his first university entrance exam. His brain was literally preserved after death for scientific study."},
  {name:"Freddie Mercury",cat:"Musician",photo:"famous_people_images/9.jpg",fact:"<strong>Lead singer of Queen.</strong> His Live Aid performance in 1985 is widely called the greatest rock concert performance in history."},
  {name:"Serena Williams",cat:"Athlete",photo:"famous_people_images/10.jpg",fact:"<strong>23 Grand Slam titles.</strong> Won the Australian Open in 2017 while 8 weeks pregnant."},
  {name:"Steve Jobs",cat:"Historical / Political",photo:"famous_people_images/11.jpg",fact:"<strong>Co-founded Apple in a garage.</strong> Was fired from his own company, came back and turned it into the most valuable company on Earth."},
  {name:"Frida Kahlo",cat:"Historical / Political",photo:"famous_people_images/12.jpg",fact:"<strong>Iconic Mexican painter.</strong> Survived polio and a near-fatal bus accident. Most of her 143 paintings are self-portraits."},
  {name:"Bruce Lee",cat:"Entertainer",photo:"famous_people_images/13.jpg",fact:"<strong>Founder of Jeet Kune Do.</strong> Could do one-finger push-ups. His punches were too fast for cameras of the era to capture."},
  {name:"Nikola Tesla",cat:"Historical / Political",photo:"famous_people_images/14.jpg",fact:"<strong>Invented AC electricity.</strong> Had a rivalry with Edison so intense it was called the 'War of Currents.'"},
  {name:"Audrey Hepburn",cat:"Entertainer",photo:"famous_people_images/15.jpg",fact:"<strong>One of 16 EGOT winners ever.</strong> Survived Nazi occupation as a child. Spent her later years as a UNICEF Goodwill Ambassador."},
  {name:"Martin Luther King Jr",cat:"Historical / Political",photo:"famous_people_images/16.jpg",fact:"<strong>Led the American civil rights movement.</strong> Delivered 'I Have a Dream' at age 34. Youngest Nobel Peace Prize winner at the time."},
  {name:"Charlie Chaplin",cat:"Entertainer",photo:"famous_people_images/17.jpg",fact:"<strong>Pioneer of silent film comedy.</strong> Once entered a Charlie Chaplin lookalike contest — and came in third place."},
  {name:"Billie Holiday",cat:"Musician",photo:"famous_people_images/18.jpg",fact:"<strong>One of the greatest jazz vocalists ever.</strong> Her 1939 recording of 'Strange Fruit' was called the song of the century by Time magazine."},
  {name:"Usain Bolt",cat:"Athlete",photo:"famous_people_images/19.jpg",fact:"<strong>World's fastest human.</strong> Set the 100m world record of 9.58 seconds in 2009. Doctors said his scoliosis should have stopped him."},
  {name:"Coco Chanel",cat:"Historical / Political",photo:"famous_people_images/20.jpg",fact:"<strong>Revolutionized women's fashion.</strong> Grew up in an orphanage. Invented the little black dress and Chanel No. 5."},
  {name:"Leonardo da Vinci",cat:"Historical / Political",photo:"famous_people_images/21.jpg",fact:"<strong>Renaissance polymath.</strong> Painted the Mona Lisa and designed flying machines centuries ahead of their time."},
  {name:"Isaac Newton",cat:"Historical / Political",photo:"famous_people_images/22.jpg",fact:"<strong>Formulated laws of motion and gravity.</strong> Discovered calculus independently and studied optics with prisms."},
  {name:"Mahatma Gandhi",cat:"Historical / Political",photo:"famous_people_images/23.jpg",fact:"<strong>Led India's non-violent independence.</strong> Walked 240 miles for salt march against British rule."},
  {name:"Marie Curie",cat:"Historical / Political",photo:"famous_people_images/24.jpg",fact:"<strong>Discovered radium and polonium.</strong> First woman to win a Nobel Prize, and the only person to win in two sciences."},
  {name:"William Shakespeare",cat:"Historical / Political",photo:"famous_people_images/25.jpg",fact:"<strong>Master playwright and poet.</strong> Wrote 37 plays and 154 sonnets, inventing over 1,700 words in English."},
  {name:"Abraham Lincoln",cat:"Historical / Political",photo:"famous_people_images/26.jpg",fact:"<strong>Preserved the Union during Civil War.</strong> Issued Emancipation Proclamation and delivered Gettysburg Address."},
  {name:"Wolfgang Amadeus Mozart",cat:"Musician",photo:"famous_people_images/27.jpg",fact:"<strong>Child prodigy composer.</strong> Composed his first symphony at age 8 and over 600 works total."},
  {name:"Ludwig van Beethoven",cat:"Musician",photo:"famous_people_images/28.jpg",fact:"<strong>Deaf symphony composer.</strong> Wrote nine symphonies despite losing hearing, including the iconic Ninth."},
  {name:"Vincent van Gogh",cat:"Historical / Political",photo:"famous_people_images/29.jpg",fact:"<strong>Post-impressionist painter.</strong> Sold only one painting in life but created over 2,000 artworks, including Starry Night."},
  {name:"Charles Darwin",cat:"Historical / Political",photo:"famous_people_images/30.jpg",fact:"<strong>Developed evolution theory.</strong> Voyage on Beagle inspired On the Origin of Species, revolutionizing biology."},
  {name:"Thomas Edison",cat:"Historical / Political",photo:"famous_people_images/31.jpg",fact:"<strong>Invented practical light bulb.</strong> Held 1,093 patents, including phonograph and motion pictures."},
  {name:"Alexander the Great",cat:"Historical / Political",photo:"famous_people_images/32.jpg",fact:"<strong>Conquered ancient world.</strong> Built empire from Greece to India, founding 20 cities named after himself."},
  {name:"Julius Caesar",cat:"Historical / Political",photo:"famous_people_images/33.jpg",fact:"<strong>Roman conqueror and dictator.</strong> Crossed Rubicon to start civil war, reformed calendar still in use."},
  {name:"Cleopatra",cat:"Historical / Political",photo:"famous_people_images/34.jpg",fact:"<strong>Last pharaoh of Egypt.</strong> Ruled with intelligence, seducing Caesar and Antony to protect her kingdom."},
  {name:"Napoleon Bonaparte",cat:"Historical / Political",photo:"famous_people_images/35.jpg",fact:"<strong>French emperor conqueror.</strong> Spread revolutionary ideas across Europe but exiled twice."},
  {name:"Winston Churchill",cat:"Historical / Political",photo:"famous_people_images/36.jpg",fact:"<strong>WWII British leader.</strong> Inspired nation with speeches, won Nobel for literature."},
  {name:"George Washington",cat:"Historical / Political",photo:"famous_people_images/37.jpg",fact:"<strong>First U.S. President.</strong> Led Revolution to victory, set presidential precedents like two-term limit."},
  {name:"Franklin D. Roosevelt",cat:"Historical / Political",photo:"famous_people_images/38.jpg",fact:"<strong>Depression and WWII President.</strong> Elected four times, launched New Deal and Lend-Lease."},
  {name:"John F. Kennedy",cat:"Historical / Political",photo:"famous_people_images/39.jpg",fact:"<strong>Youngest U.S. President.</strong> Inspired space race with Moon goal, assassinated in 1963."},
  {name:"Malala Yousafzai",cat:"Historical / Political",photo:"famous_people_images/40.jpg",fact:"<strong>Girls' education advocate.</strong> Survived Taliban shooting, youngest Nobel laureate at 17."},
  {name:"Mother Teresa",cat:"Historical / Political",photo:"famous_people_images/41.jpg",fact:"<strong>Saint of the poor.</strong> Founded Missionaries of Charity, served Kolkata's destitute."},
  {name:"Dalai Lama",cat:"Historical / Political",photo:"famous_people_images/42.jpg",fact:"<strong>Tibetan spiritual leader.</strong> Exiled since 1959, promotes compassion and non-violence worldwide."},
  {name:"Elon Musk",cat:"Historical / Political",photo:"famous_people_images/43.jpg",fact:"<strong>SpaceX and Tesla CEO.</strong> Aims to colonize Mars, revolutionized electric cars and rockets."},
  {name:"Bill Gates",cat:"Historical / Political",photo:"famous_people_images/44.jpg",fact:"<strong>Microsoft co-founder.</strong> World's richest for years, now philanthropist via Gates Foundation."},
  {name:"Mark Zuckerberg",cat:"Historical / Political",photo:"famous_people_images/45.jpg",fact:"<strong>Facebook creator.</strong> Built social network from dorm, now Meta CEO facing privacy battles."},
  {name:"Jeff Bezos",cat:"Historical / Political",photo:"famous_people_images/46.jpg",fact:"<strong>Amazon founder.</strong> Started in garage, became e-commerce giant and space tourist."},
  {name:"Stephen Hawking",cat:"Historical / Political",photo:"famous_people_images/47.jpg",fact:"<strong>Black hole theorist.</strong> ALS paralyzed him but he wrote A Brief History of Time."},
  {name:"Neil Armstrong",cat:"Historical / Political",photo:"famous_people_images/48.jpg",fact:"<strong>First Moon walker.</strong> Apollo 11 astronaut, 'one small step' echoed globally."},
  {name:"Rosa Parks",cat:"Historical / Political",photo:"famous_people_images/49.jpg",fact:"<strong>Civil rights spark.</strong> Bus seat refusal ignited Montgomery boycott, 'mother of freedom'."},
  {name:"Amelia Earhart",cat:"Historical / Political",photo:"famous_people_images/50.jpg",fact:"<strong>Aviation pioneer.</strong> First woman to fly solo Atlantic, vanished over Pacific in 1937."},
  {name:"Pablo Picasso",cat:"Historical / Political",photo:"famous_people_images/51.jpg",fact:"<strong>Cubism co-founder.</strong> Painted Guernica protesting war, over 50,000 works created."},
  {name:"Salvador Dalí",cat:"Historical / Political",photo:"famous_people_images/52.jpg",fact:"<strong>Surrealist artist.</strong> Melting clocks in Persistence of Memory, eccentric mustache icon."},
  {name:"Michelangelo",cat:"Historical / Political",photo:"famous_people_images/53.jpg",fact:"<strong>Renaissance sculptor.</strong> Carved David and painted Sistine Chapel ceiling from scaffolding."},
  {name:"Galileo Galilei",cat:"Historical / Political",photo:"famous_people_images/54.jpg",fact:"<strong>Heliocentrism advocate.</strong> Telescope inventor, condemned by Church for Earth not center."},
  {name:"Socrates",cat:"Historical / Political",photo:"famous_people_images/55.jpg",fact:"<strong>Western philosophy founder.</strong> Questioning method led to execution by hemlock for 'corrupting youth'."},
  {name:"Plato",cat:"Historical / Political",photo:"famous_people_images/56.jpg",fact:"<strong>Academy founder.</strong> Student of Socrates, wrote Republic on ideal society."},
  {name:"Aristotle",cat:"Historical / Political",photo:"famous_people_images/57.jpg",fact:"<strong>Ancient polymath.</strong> Tutored Alexander, founded Lyceum, influenced science and ethics."},
  {name:"Confucius",cat:"Historical / Political",photo:"famous_people_images/58.jpg",fact:"<strong>Chinese ethics teacher.</strong> Analects guide governance and morality for millennia."},
  {name:"Laozi",cat:"Historical / Political",photo:"famous_people_images/59.jpg",fact:"<strong>Taoism originator.</strong> Tao Te Ching on harmony, possibly mythical figure."},
  {name:"Buddha",cat:"Historical / Political",photo:"famous_people_images/60.jpg",fact:"<strong>Buddhism founder.</strong> Enlightenment under tree, Four Noble Truths end suffering."},
  {name:"Jesus Christ",cat:"Historical / Political",photo:"famous_people_images/61.jpg",fact:"<strong>Christianity central figure.</strong> Miracles and resurrection teachings shaped world religion."},
  {name:"Muhammad",cat:"Historical / Political",photo:"famous_people_images/62.jpg",fact:"<strong>Islam prophet.</strong> Revelations from Gabriel, unified Arabia, Quran foundation."},
  {name:"Joan of Arc",cat:"Historical / Political",photo:"famous_people_images/63.jpg",fact:"<strong>French military saint.</strong> Led army at 17, burned by English but canonized."},
  {name:"Queen Elizabeth I",cat:"Historical / Political",photo:"famous_people_images/64.jpg",fact:"<strong>Elizabethan England ruler.</strong> Defeated Armada, Golden Age of exploration and arts."},
  {name:"Queen Victoria",cat:"Historical / Political",photo:"famous_people_images/65.jpg",fact:"<strong>Victorian Era monarch.</strong> Longest reign, empire peak, widowed at 42."},
  {name:"Catherine the Great",cat:"Historical / Political",photo:"famous_people_images/66.jpg",fact:"<strong>Russian empire expander.</strong> Enlightened reforms, coup to throne, vast territories added."},
  {name:"Simon Bolivar",cat:"Historical / Political",photo:"famous_people_images/67.jpg",fact:"<strong>South America liberator.</strong> Freed Venezuela, Colombia, etc., 'El Libertador'."},
  {name:"Che Guevara",cat:"Historical / Political",photo:"famous_people_images/68.jpg",fact:"<strong>Cuban revolution icon.</strong> With Castro, global rebellion symbol, executed in Bolivia."},
  {name:"Fidel Castro",cat:"Historical / Political",photo:"famous_people_images/69.jpg",fact:"<strong>Cuba's long ruler.</strong> Overthrew Batista, 49-year communist regime."},
  {name:"Mao Zedong",cat:"Historical / Political",photo:"famous_people_images/70.jpg",fact:"<strong>China's communist founder.</strong> Long March survivor, Cultural Revolution chaos."},
  {name:"Joseph Stalin",cat:"Historical / Political",photo:"famous_people_images/71.jpg",fact:"<strong>Soviet dictator.</strong> Industrialized USSR, purges killed millions."},
  {name:"Adolf Hitler",cat:"Musician",photo:"famous_people_images/72.jpg",fact:"<strong>Nazi Germany leader.</strong> WWII instigator, Holocaust architect."},
  {name:"Elvis Presley",cat:"Musician",photo:"famous_people_images/73.jpg",fact:"<strong>Rock 'n' roll king.</strong> 'The Pelvis' sold billion records, cultural phenomenon."},
  {name:"The Beatles",cat:"Musician",photo:"famous_people_images/74.jpg",fact:"<strong>Music revolution band.</strong> Sgt. Pepper's changed pop, Fab Four broke up in 1970."},
  {name:"Michael Jackson",cat:"Musician",photo:"famous_people_images/75.jpg",fact:"<strong>Pop king.</strong> Thriller best-seller, moonwalk inventor, child abuse scandals."},
  {name:"Bob Dylan",cat:"Musician",photo:"famous_people_images/76.jpg",fact:"<strong>Folk protest singer.</strong> Nobel winner, Blowin' in the Wind anthem."},
  {name:"David Bowie",cat:"Musician",photo:"famous_people_images/77.jpg",fact:"<strong>Rock chameleon.</strong> Ziggy Stardust, 100 million records, gender-bending icon."},
  {name:"Madonna",cat:"Musician",photo:"famous_people_images/78.jpg",fact:"<strong>Pop reinvention queen.</strong> Material Girl, 12 #1 hits, provocative videos."},
  {name:"Prince",cat:"Musician",photo:"famous_people_images/79.jpg",fact:"<strong>Musical virtuoso.</strong> Purple Rain, played 27 instruments, fought label battles."},
  {name:"Whitney Houston",cat:"Musician",photo:"famous_people_images/80.jpg",fact:"<strong>Vocal powerhouse.</strong> I Will Always Love You, 7 Grammys, tragic overdose."},
  {name:"Aretha Franklin",cat:"Musician",photo:"famous_people_images/81.jpg",fact:"<strong>Soul queen.</strong> Respect anthem, first woman in Rock Hall, 18 Grammys."},
  {name:"Stevie Wonder",cat:"Musician",photo:"famous_people_images/82.jpg",fact:"<strong>Blind musical genius.</strong> 25 Grammys, Superstition, Motown prodigy."},
  {name:"Ray Charles",cat:"Musician",photo:"famous_people_images/83.jpg",fact:"<strong>Soul pioneer.</strong> Georgia on My Mind, overcame blindness, 17 Grammys."},
  {name:"Louis Armstrong",cat:"Musician",photo:"famous_people_images/84.jpg",fact:"<strong>Jazz trumpet legend.</strong> What a Wonderful World, scat innovator."},
  {name:"Miles Davis",cat:"Musician",photo:"famous_people_images/85.jpg",fact:"<strong>Jazz trumpet innovator.</strong> Kind of Blue, modal jazz pioneer."},
  {name:"John Coltrane",cat:"Musician",photo:"famous_people_images/86.jpg",fact:"<strong>Jazz sax spiritualist.</strong> A Love Supreme, spiritual quest through music."},
  {name:"Ella Fitzgerald",cat:"Musician",photo:"famous_people_images/87.jpg",fact:"<strong>Jazz songstress.</strong> Scat queen, 13 Grammys, 'First Lady of Song'."},
  {name:"Frank Sinatra",cat:"Musician",photo:"famous_people_images/88.jpg",fact:"<strong>Crooner icon.</strong> My Way, Rat Pack, Vegas residency king."},
  {name:"Bob Marley",cat:"Musician",photo:"famous_people_images/89.jpg",fact:"<strong>Reggae peace prophet.</strong> One Love, Jamaica's voice, cancer at 36."},
  {name:"Jimi Hendrix",cat:"Musician",photo:"famous_people_images/90.jpg",fact:"<strong>Guitar virtuoso.</strong> Woodstock's Star-Spangled Banner, lefty upside-down play."},
  {name:"Kurt Cobain",cat:"Musician",photo:"famous_people_images/91.jpg",fact:"<strong>Grunge frontman.</strong> Nirvana's Smells Like Teen Spirit, suicide at 27."},
  {name:"Tupac Shakur",cat:"Musician",photo:"famous_people_images/92.jpg",fact:"<strong>Rap revolutionary.</strong> All Eyez on Me, thug life philosophy, murdered at 25."},
  {name:"The Notorious B.I.G.",cat:"Musician",photo:"famous_people_images/93.jpg",fact:"<strong>East Coast rap king.</strong> Ready to Die, Biggie Smalls, killed in drive-by."},
  {name:"Jay-Z",cat:"Musician",photo:"famous_people_images/94.jpg",fact:"<strong>Rap mogul.</strong> 99 Problems, Roc-A-Fella founder, married Beyoncé."},
  {name:"Kanye West",cat:"Musician",photo:"famous_people_images/95.jpg",fact:"<strong>Rap producer mogul.</strong> Graduation, Yeezy fashion, controversial outbursts."},
  {name:"Taylor Swift",cat:"Musician",photo:"famous_people_images/96.jpg",fact:"<strong>Pop songwriting star.</strong> 11 Grammys, Eras Tour, narrative albums."},
  {name:"Cristiano Ronaldo",cat:"Musician",photo:"famous_people_images/97.jpg",fact:"<strong>Football superstar.</strong> 5 Ballon d'Or, Real Madrid legend, global icon."},
  {name:"Lionel Messi",cat:"Musician",photo:"famous_people_images/98.jpg",fact:"<strong>Argentine football genius.</strong> 7 Ballon d'Or, Barcelona maestro, World Cup winner."},
  {name:"Pele",cat:"Musician",photo:"famous_people_images/99.jpg",fact:"<strong>Brazilian football king.</strong> 3 World Cups, Santos legend, 'O Rei'."},
  {name:"Diego Maradona",cat:"Athlete",photo:"famous_people_images/100.jpg",fact:"<strong>Argentine football wizard.</strong> Hand of God goal, Napoli savior, drug struggles."},
  {name:"Roger Federer",cat:"Athlete",photo:"famous_people_images/101.jpg",fact:"<strong>Tennis elegance.</strong> 20 Grand Slams, Swiss grace, 310 weeks #1."},
  {name:"Rafael Nadal",cat:"Athlete",photo:"famous_people_images/102.jpg",fact:"<strong>Clay court king.</strong> 22 Grand Slams, Roland Garros master, warrior spirit."},
  {name:"Tiger Woods",cat:"Athlete",photo:"famous_people_images/103.jpg",fact:"<strong>Golf dominance.</strong> 15 Majors, comeback from scandal, revolutionized sport."}
];
